### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by mkcmr** [wyzxxz/heapdump_tool#13]
file: heapdump
[-] Start jhat, waiting...
find compressed file. start unzip file...
java.util.zip.ZipException: Not in GZIP format
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at heapdump.Main.unZipFiles(Main.java:1903)
        at heapdump.Main.checkServer(Main.java:1406)
        at heapdump.Main.main(Main.java:102)
请手工解压 heapdump 文件后尝试
jhat fail.
error message: Reading from heapdump...
java.io.IOException: Unrecognized magic number: 1013084704
        at com.sun.tools.hat.internal.parser.Reader.readFile(Reader.java:94)
        at com.sun.tools.hat.Main.main(Main.java:159)

**Comment by wyzxxz** [comment]
heapdump文件有错误，不兼容，尝试重新下载一下，或者用Eclipse Memory Analyzer这个试试
