### ISSUE TITLE
Unrecognized heap dump sub-record type:  202

### ISSUE THREAD

**Issue by plusgua** [wyzxxz/heapdump_tool#5]
don't know why....

```
[-] file: heapdump
[-] Start jhat, waiting...
jhat fail.
error message: Reading from heapdump...
Dump file created Sat Nov 12 16:02:56 CST 2022
java.io.IOException: Unrecognized heap dump sub-record type:  202
        at com.sun.tools.hat.internal.parser.HprofReader.readHeapDump(HprofReader.java:506)
        at com.sun.tools.hat.internal.parser.HprofReader.read(HprofReader.java:238)
        at com.sun.tools.hat.internal.parser.Reader.readFile(Reader.java:92)
        at com.sun.tools.hat.Main.main(Main.java:159)


[-] exit.
```

**Comment by wyzxxz** [comment]
heapdump文件下载的时候是不是有网络错误，导致文件不完整

**Comment by wyzxxz** [comment]
重新下载heapdump文件试下
